"""PDF security report generation."""

from datetime import datetime, timedelta, timezone
from io import BytesIO

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors

from app.db.session import get_db
from app.models import User, Event, Camera, Alert
from app.core.security import require_permission
from app.services.ai_search import build_summary

router = APIRouter(prefix="/api/reports", tags=["reports"])


@router.get("/daily.pdf")
def daily_pdf(
    db: Session = Depends(get_db),
    _: User = Depends(require_permission("reports:export")),
):
    summary = build_summary(db, 24)
    since = datetime.now(timezone.utc) - timedelta(hours=24)
    events = db.query(Event).filter(Event.timestamp >= since).order_by(Event.timestamp.desc()).limit(40).all()
    cameras = {c.id: c.name for c in db.query(Camera).all()}
    alerts = db.query(Alert).filter(Alert.is_active == True).count()  # noqa: E712

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="AetherShield Daily Security Report")
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], textColor=colors.HexColor("#0f172a"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#1e293b"))
    body = styles["BodyText"]

    story = []
    story.append(Paragraph("AetherShield VMS — Daily Security Report", title_style))
    story.append(Paragraph(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), body))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Executive Summary", h2))
    for line in summary["summary_text"].split("\n"):
        story.append(Paragraph(line.replace("- ", "• "), body))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("Highlights", h2))
    for h in summary["highlights"]:
        story.append(Paragraph(f"• {h}", body))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(f"Active alerts: {alerts}", body))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Recent Events", h2))

    table_data = [["Time (UTC)", "Camera", "Event", "Priority", "Conf"]]
    for e in events:
        table_data.append([
            e.timestamp.strftime("%H:%M:%S"),
            cameras.get(e.camera_id, str(e.camera_id)),
            e.label[:40],
            e.priority,
            f"{e.confidence:.0%}",
        ])
    table = Table(table_data, colWidths=[1.1 * inch, 1.3 * inch, 2.4 * inch, 0.9 * inch, 0.6 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph("Generated by AetherShield VMS — confidential.", body))
    doc.build(story)
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=aethershield_daily_report.pdf"},
    )
